/**
 * Copyright (c) The openTCS Authors.
 *
 * This program is free software and subject to the MIT license. (For details,
 * see the licensing information (LICENSE.txt) you should have received with
 * this copy of the software.)
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uwant.vehicle.route.edit;

/** @author zhuchang */
@SuppressWarnings("this-escape")
public class RouteAddPanel extends javax.swing.JPanel {

  /** Creates new form RouteAddPanel */
  public RouteAddPanel() {
    initComponents();
  }

  public int getRouteId() {
    return Integer.valueOf(routeIdFormattedTextField.getText());
  }

  public void setRoutId(int routeId) {
    routeIdFormattedTextField.setText(Integer.toString(routeId));
  }

  public int getNodeCount() {
    return Integer.valueOf(nodeCountFormattedTextField.getText());
  }

  public void setNodeCount(int nodeCount) {
    nodeCountFormattedTextField.setText(Integer.toString(nodeCount));
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    routeIdLabel = new javax.swing.JLabel();
    nodeCountLabel = new javax.swing.JLabel();
    routeIdFormattedTextField = new javax.swing.JFormattedTextField();
    nodeCountFormattedTextField = new javax.swing.JFormattedTextField();

    java.util.ResourceBundle bundle =
        java.util.ResourceBundle.getBundle("i18n/uwant/vehicle/commadapter/Bundle"); // NOI18N
    routeIdLabel.setText(bundle.getString("RouteAddPanel.routeIdLabel")); // NOI18N

    nodeCountLabel.setText(bundle.getString("RouteAddPanel.nodeCountLabel")); // NOI18N

    routeIdFormattedTextField.setFormatterFactory(
        new javax.swing.text.DefaultFormatterFactory(
            new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

    nodeCountFormattedTextField.setFormatterFactory(
        new javax.swing.text.DefaultFormatterFactory(
            new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
    nodeCountFormattedTextField.setText("5");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nodeCountLabel)
                            .addComponent(routeIdLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(
                                routeIdFormattedTextField,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                98,
                                Short.MAX_VALUE)
                            .addComponent(nodeCountFormattedTextField))
                    .addContainerGap(70, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(routeIdLabel)
                            .addComponent(
                                routeIdFormattedTextField,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nodeCountLabel)
                            .addComponent(
                                nodeCountFormattedTextField,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(40, Short.MAX_VALUE)));
  } // </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JFormattedTextField nodeCountFormattedTextField;
  private javax.swing.JLabel nodeCountLabel;
  private javax.swing.JFormattedTextField routeIdFormattedTextField;
  private javax.swing.JLabel routeIdLabel;
  // End of variables declaration//GEN-END:variables
}
